## Project information
site_name: Regolamento del Bilancio in Democrazia Partecipata del Comune di San Giuseppe Jato
site_url: https://regolamento-bilancio-democrazia-partecipata-sangiuseppejato.readthedocs.io/it/latest/
site_description: Regolamento del Bilancio in Democrazia Partecipata del Comune di San Giuseppe Jato
site_author: Giuesppe Ragusa
## Repository
repo_url: https://github.com/giuragu/regolamento-bilancio-democrazia-partecipata-sangiuseppejato
repo_name: regolamento-bilancio-democrazia-partecipata-sangiuseppejato
edit_uri: edit/master/docs/

theme:
  name: "material"
  logo: images/logo3.png
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  language: it
  features:
    - navigation.top
  icon:
     repo: fontawesome/brands/github
  
  
  
nav:
  - Home: README.md
  - Articolo 1 - Principi e finalità: articolo-1.md
  - Articolo 2 - Aventi diritto al voto: articolo-2.md
  - Articolo 3 - Fasi del Bilancio Partecipativo: articolo-3.md
  - Articolo 4 - Definizione del budget: articolo-4.md
  - Articolo 5 - Informazione: articolo-5.md
  - Articolo 6 - Modalità di espressioni della preferenza: articolo-6.md
  - Articolo 7 - Criteri di valutazione delle attività: articolo-7.md
  - Articolo 8 - Verbale di partecipazione: articolo-8.md
  - Articolo 9 - Aree tematiche: articolo-9.md
  - Articolo 10 - Entrata in vigore: articolo-10.md
  - Articolo 11 - Informativa sul trattamento dei dati personali: articolo-11.md
  - Articolo 12 - Pubblicità del Regolamento: articolo-12.md
  - Articolo 13 - Revisione del Regolamento: articolo-13.md

 

plugins:
- search
- mkdocstrings


# Extensions
markdown_extensions:
- mkdocs-click
- pymdownx.highlight
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.critic:
      mode: view
- pymdownx.betterem:
      smart_enable: all
- pymdownx.caret
- pymdownx.mark
- pymdownx.tilde
- pymdownx.smartsymbols
- admonition
- pymdownx.details
- pymdownx.tasklist:
      clickable_checkbox: true
- footnotes
- attr_list
- def_list 
- pymdownx.inlinehilite
  

## Social Media
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/cirospat
    - icon: fontawesome/brands/github-alt
      link: https://github.com/cirospat/rtd-comemipiace
    - icon: fontawesome/solid/envelope
      link: mailto:cirospat@gmail.com
    - icon: fontawesome/solid/book
      link: https://readthedocs.org/projects/rtd-comemipiace/
  
## setting dal progetto originale https://github.com/up42/up42-py/blob/master/mkdocs.yml + https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml

## copiright
copyright: <a href="https://twitter.com/cirospat" title="Ciro Spataro " target="_blank">Ciro Spataro </a> | 2021 | CC BY 4.0 Int Licence
