## Project information
site_name: Innovazione PA, quello che il cittadino non sempre vede
site_url: https://innovazionepa-flaviamarzano.readthedocs.io/it/latest/
site_description: Innovazione PA, quello che il cittadino non sempre vede
site_author: Flavia Marzano

## Repository
# repo_url: https://github.com/cirospat/mkdocs-flavia_marzano
# repo_name: mkdocs-flavia_marzano
# edit_uri: edit/master/docs/

## Configuration
theme:
  name: "material"
  custom_dir: docs/overrides/
  logo: images/flaviamarzano.jpg
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  language: it
  features:
    - navigation.top
    - navigation.instant
    - search.suggest
    - search.highlight
    - search.share
  icon:
     repo: fontawesome/brands/github
  favicon: images/favicon.ico
  
  
  
nav:
  - Home: README.md
  - Ho visto cose: 1-ho-visto-cose.md
  - Quale formazione e a chi: 2-quale-formazione-e-a-chi.md
  - Open Governmente Partnership: 3-open-government-partnership.md
  - Roma semplice: 4-roma-semplice.md
  - Software libero e superamento dei lock in: 5-software-libero-superamento-lockin.md
  - Inclusione digitale nei punti Roma facile: 6-inclusione-digitale-punti-roma-facile.md
  - Iniziative e progetti di partecipazione: 7-iniziative-progetti-partecipazione.md
  - Trasparenza, open data e acccountability: 8-trasparenza-opendata-accountability.md
  - Flavia Marzano: 9-flavia-marzano.md
 

plugins:
- search
- mkdocstrings


# Extensions
markdown_extensions:
- mkdocs-click
- pymdownx.highlight
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.critic:
      mode: view
- pymdownx.betterem:
      smart_enable: all
- pymdownx.caret
- pymdownx.mark
- pymdownx.tilde
- pymdownx.smartsymbols
- admonition
- pymdownx.details
- pymdownx.tasklist:
      clickable_checkbox: true
- footnotes
- attr_list
- def_list 
- pymdownx.inlinehilite
- meta
- md_in_html
  
  
## extra CSS
extra_css:
   - stylesheets/extra.css


## Custom theme additions
extra_javascript:
   - stylesheets/extra.js

disqus: ods-mkdocs-material
##  ods-mkdocs-material è lo <shortname> legato a Disqus

## Social Media
extra:
## Come inserire i commenti di Disqus https://squidfunk.github.io/mkdocs-material/setup/adding-a-comment-system/#other-comment-systems
## Crea accont e sito shortname https://help.disqus.com/en/articles/1717111-what-s-a-shortname
## disqus: <shortname>
  disqus: reg-dem-part-sgj
##  reg-dem-part-sgj è lo <shortname> legato a Disqus
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/cirospat/mkdocs-flavia_marzano
      name: Repository Github
    - icon: fontawesome/solid/envelope
      link: mailto:flavia.marzano@gmail.com
      name: Posta Celettronica di Flavia Marzano
    - icon: fontawesome/solid/book
      link: https://readthedocs.org/projects/innovazionepa-flaviamarzano
      name: Progetto Read the docs

  
## setting dal progetto originale https://github.com/up42/up42-py/blob/master/mkdocs.yml + https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml

## copiright
copyright: <a href="https://www.theinnovationgroup.it/speakers/flavia-marzano/?lang=it" title="Flavia Marzano " target="_blank"> Flavia Marzano </a> | <a href="https://creativecommons.org/licenses/by/4.0/deed.it" title="Attribuzione 4.0 Internazionale (CC BY 4.0)" target="_blank"> CC BY 4.0 Int Licence</a>

